services:
  server:
    container_name: server
    image: ryanali12/sti-munoz-library-server
    ports:
      - "5200:5200"
    volumes:
      - ./server:/go/dev
    environment:
      MIGRATE: ${DB_DRIVER}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_APP_URL: ${ADMIN_APP_URL}
      CLIENT_APP_URL: ${CLIENT_APP_URL}
      SCANNER_APP_URL: ${SCANNER_APP_URL}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_DEFAULT_BUCKET: ${S3_DEFAULT_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE}
      S3_DISABLE_SSL: ${S3_DISABLE_SSL}
      ADMIN_APP_CLIENT_ID: ${ADMIN_APP_CLIENT_ID}
      ADMIN_APP_TENANT_ID: ${ADMIN_APP_TENANT_ID}
      ADMIN_APP_ID: ${ADMIN_APP_ID}
      CLIENT_APP_CLIENT_ID: ${CLIENT_APP_CLIENT_ID}
      CLIENT_APP_TENANT_ID: ${CLIENT_APP_TENANT_ID}
      CLIENT_APP_ID: ${CLIENT_APP_ID}
      CLIENT_ID: ${API_APP_CLIENT_ID}
      APP_ID: ${API_APP_ID}
      TENANT_ID: ${API_APP_TENANT_ID}
      CRYPTO_SECRET: ${CRYPTO_SECRET}
      GIN_MODE: debug #release
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      SCANNER_APP_DOMAIN: ${SCANNER_APP_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_URL: ${SERVER_URL}
      S3_URL: ${S3_URL}
    depends_on:
      - postgres
      - rabbitmq
  admin_app:
    container_name: admin_app
    image: ryanali12/sti-munoz-library-admin-app
    ports:
      - "5201:5201"
    volumes:
      - ./admin_app/src:/node/dev/admin/src
      - ./admin_app/vite.config.ts:/node/dev/admin/vite.config.ts
      - ./admin_app/tailwind.config.cjs:/node/dev/admin/tailwind.config.cjs
    depends_on:
      - server
    environment:
      VITE_REDIRECT_URI: ${ADMIN_APP_URL}
      VITE_CLIENT_ID: ${ADMIN_APP_CLIENT_ID}
      VITE_TENANT_ID: ${ADMIN_APP_TENANT_ID}
      VITE_API_CLIENT_ID: ${API_APP_CLIENT_ID}
      VITE_SERVER_URL: ${SERVER_URL}
      VITE_WS_URL: ${WS_URL}
      VITE_S3_URL: ${S3_URL}
  client_app:
    container_name: client_app
    image: ryanali12/sti-munoz-library-client-app
    ports:
      - "5202:5202"
    volumes:
      - ./client_app/src:/node/dev/client/src
      - ./client_app/vite.config.ts:/node/dev/client/vite.config.ts
      - ./client_app/tailwind.config.cjs:/node/dev/client/tailwind.config.cjs
    depends_on:
      - server
    environment:
      VITE_REDIRECT_URI: ${CLIENT_APP_URL}
      VITE_SERVER_URL: ${SERVER_URL}
      VITE_CLIENT_ID: ${CLIENT_APP_CLIENT_ID}
      VITE_TENANT_ID: ${CLIENT_APP_TENANT_ID}
      VITE_API_CLIENT_ID: ${API_APP_CLIENT_ID}
      VITE_WS_URL: ${WS_CLIENT_URL}
      VITE_S3_URL: ${S3_URL}
  scanner_app:
    container_name: scanner_app
    image: ryanali12/sti-munoz-library-scanner-app
    ports:
      - "5209:5209"
    volumes:
      - ./scanner_app/src:/node/dev/scanner/src
    depends_on:
      - server
    environment:
      VITE_SERVER_URL: ${SERVER_URL}
  postgres:
    container_name: postgres
    restart: always
    image: postgres:17.2-alpine3.21
    ports:
      - "5203:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./pgadmin:/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5204:80"
  rabbitmq:
    image: rabbitmq:3.11.9-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5205:5672"
      - "5206:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  minio:
    container_name: libraryminio
    image: minio/minio
    ports:
      - "5207:9000"
      - "5208:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server --console-address ":9001" /data
