FROM node:19-alpine3.16 as builder


WORKDIR /node/prod/client

COPY . .

RUN npm install && npm run build


FROM nginx:1.23.4-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*


COPY --from=builder /node/prod/client/dist /usr/share/nginx/html

EXPOSE 5202

ENTRYPOINT ["nginx", "-g", "daemon off;"]
