ALTER TABLE IF EXISTS catalog.book
ALTER COLUMN isbn SET DEFAULT '',
ALTER COLUMN description SET DEFAULT '',
ALTER COLUMN cost_price SET DEFAULT 0,
ALTER COLUMN edition SET DEFAULT 0,
ALTER COLUMN year_published SET DEFAULT 0,
ALTER COLUMN ddc SET DEFAULT '',
ALTER COLUMN author_number SET DEFAULT ''